### PR TITLE
removing underscore from source

### PR DESCRIPTION
**Pull request by rjriel**
Fixes #[issue number].

### Status
```
[ ] Under development
[x] Waiting for code review
[ ] Waiting for merge
```
### Information
```
[ ] Contains breaking changes
[ ] Contains new API(s)
[ ] Contains documentation
[ ] Contains test
```
### To-do list
```
[x] Needs To Be Tested
[ ] [Fix another thing]
[ ] ...
```

### CODE REVIEW

**Comment by stefanwalther** [comment]
As both libraries are included in Qlik Sense, why do you want to remove this dependency?

**Comment by rjriel** [comment]
After discussion internally I don't think the underscore library is covered by Qlik Support, so I thought removing the dependency would be good

**Comment by stefanwalther** [comment]
Just a general notice; I hope you are not evaluating the master branch, but the v1 branch, this is the new one which should be included in the Cloud (as I have several times mentioned before).

**Comment by rjriel** [comment]
don't recall seeing v1 anywhere, but let's close this PR then and I'll restart w/ v1.0

**Comment by stefanwalther** [comment]
https://github.com/stefanwalther/sense-navigation/pull/58 resp https://github.com/stefanwalther/sense-navigation/tree/v1.0

**Comment by stefanwalther** [comment]
You have deleted the pull-request, so I'll do it on my own.

**Pull request closed without merging**
