### PR TITLE
Removing underscore from source

### PR DESCRIPTION
**Pull request by rjriel**
### Status
```
[ ] Under development
[x] Waiting for code review
[ ] Waiting for merge
```
### Information
```
[ ] Contains breaking changes
[ ] Contains new API(s)
[ ] Contains documentation
[ ] Contains test
```
### To-do list
```
[ ] [Fix this thing]
[ ] [Fix another thing]
[ ] ...
```

Note*: This does not include removing underscore from the files pulled in from the sense-extension-utils repo. Those need to be addressed separately.

### CODE REVIEW

**Comment by stefanwalther** [comment]
To be honest, I am very hesitant of merging this PR, as this is not the full story. Dependent libraries such as extension-utils also use underscore, so the changes would have to be made there, too.
It feels like developing a lodash-/underscore-light for this purpose and that feels pretty stupid and unnecessary work.

Before removing underscore, I'd rather load underscore as a separate module (but then I certainly have to deal with conflicting versions).


Personally I'd much more prefer an option in the future, where I can run my extension against the edge-versions of Qlik Sense / Qlik Cloud, so that I could see if something breaks and even undocumented internal modules (like underscore) got removed ...

Thoughts?

**Comment by rjriel** [comment]
I do agree it feels a little clunky writing an isEmpty function to replace the underscore library. If by (load underscore as a separate module) you mean the same way you do the utils (ie. putting it into an external lib folder and referencing that) I think that would be a good idea.

As far as the idea of having an option to run extensions against edge versions, while it sounds like a good idea in general, although it wouldn't change our thoughts from the extension certification side.

All that being said, I still think the changes in **properties.js** are still valid since all I was doing there to remove underscore was converting to use standard javascript Array functions

**Comment by stefanwalther** [comment]
Tasks to solve this:

- [ ] Remove underscore dependency in sense-navigation
- [ ] Remove underscore dependency in sense-extension-utils

**Comment by rjriel** [comment]
Makes sense. May I recommend using npm as the source to pull the needed libraries in from? not only is it easy to just load what's needed (ie. `npm install lodash.isempty`) but in certification we're looking at one of the requirements (or recommendations) for third party libraries be to use npm since we'd like to leverage products like snyk.io to keep track of security issues that may crop up.

I'm not sure if we want to close this PR and create an issue surrounding this or leave this open for the time being

**Comment by stefanwalther** [comment]
> May I recommend using npm as the source to pull the needed libraries in from?
Sure, will do that.

**Comment by stefanwalther** [comment]
Some of the tasks above are not done; still working on it.

**Comment by rjriel** [comment]
ya, didn't mean to actually close this...I deleted the branch in my fork and it automatically closed the PR.

**Comment by stefanwalther** [comment]
np, will track it somewhere else.

**Pull request closed without merging**
